x-logging: &default-logging
    driver: "json-file"
    options:
        max-size: "10m"
        max-file: "3"

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${CLIENT_PORT:-3000}:3000"
        logging: *default-logging
        volumes:
            - ".:/app"
            - ./startup.sh:/usr/local/bin/startup.sh:ro
            - "/app/node_modules"
        networks:
            - sail

networks:
    sail:
        driver: bridge
